#!/bin/bash
# Builds dist/SaarathiDriver-v<version>.apk straight from the Android SDK tools —
# no Gradle, no Android Studio, nothing downloaded (same pipeline as Wepzite CRM).
#
#   ./build-apk.sh                      build for the server in driver.env
#   SERVER_URL=https://x.in ./build-apk.sh
#   ./build-apk.sh install              build, install on the connected phone/emulator, open it
#
# The app opens ${SERVER_URL}/admin — the same driver console as the website, so
# every change you deploy to the site shows up in the app instantly. SERVER_URL
# must be the site's APP_URL origin (sign-in and the CSRF check depend on it).
#
# Needs: a JDK (javac/keytool) and Android SDK build-tools 35 + platform 34.
#
# ⚠️  keys/ holds the signing key. Android only installs an UPDATE signed with the
# same key; losing it means uninstalling (the driver just signs in again — no data
# lives on the phone), but back keys/ up anyway (Drive + pen drive).
set -euo pipefail

VERSION_NAME="1.0.0"
VERSION_CODE=1
PACKAGE="com.saarathi.driver"

ROOT="$(cd "$(dirname "$0")" && pwd)"
[ -f "$ROOT/driver.env" ] && set -a && . "$ROOT/driver.env" && set +a
SERVER_URL="${SERVER_URL:-}"
APP_NAME="${APP_NAME:-Saarathi Driver}"
SERVER_URL="${SERVER_URL%/}"
if [ -z "$SERVER_URL" ]; then
  echo "Set SERVER_URL (e.g. https://yourdomain.in) in driver.env or the environment."; exit 1
fi
case "$SERVER_URL" in
  https://*) ;;
  http://localhost*|http://127.0.0.1*|http://10.0.2.2*) echo "  (test build: plain HTTP to $SERVER_URL)";;
  *) echo "SERVER_URL must be https:// (plain http is only allowed for localhost test builds)"; exit 1;;
esac
HOST="$(echo "$SERVER_URL" | sed -E 's#^[a-z]+://([^/:]+).*#\1#')"

SDK="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
BT="$SDK/build-tools/35.0.0"
ANDROID_JAR="$SDK/platforms/android-34/android.jar"
OUT="$ROOT/build"
APK="$ROOT/dist/SaarathiDriver-v$VERSION_NAME.apk"
KEYSTORE="$ROOT/keys/saarathi-driver.jks"
KEYPASS="$ROOT/keys/keystore-password.txt"

for f in "$BT/aapt2" "$BT/d8" "$BT/zipalign" "$BT/apksigner" "$ANDROID_JAR"; do
  [ -e "$f" ] || { echo "Missing $f — install build-tools 35.0.0 and platform android-34"; exit 1; }
done

rm -rf "$OUT" && mkdir -p "$OUT/classes" "$OUT/gen/java/com/saarathi/driver" "$OUT/genres/values" "$OUT/genres/xml" "$ROOT/dist"

echo "▸ Config for $SERVER_URL"
xml_escape() { printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e "s/'/\\\\'/g"; }
cat >"$OUT/gen/java/com/saarathi/driver/Config.java" <<EOF
package com.saarathi.driver;

/** Generated by build-apk.sh — do not edit. */
final class Config {
    static final String SERVER = "$SERVER_URL";
    static final String START = SERVER + "/admin";
    static final String VERSION = "$VERSION_NAME";

    private Config() {}
}
EOF
cat >"$OUT/genres/values/strings.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">$(xml_escape "$APP_NAME")</string>
</resources>
EOF
# HTTPS only, system CAs only; a localhost test build may use plain HTTP to that one host.
CLEAR=""
case "$SERVER_URL" in http://*) CLEAR="    <domain-config cleartextTrafficPermitted=\"true\"><domain includeSubdomains=\"false\">$HOST</domain></domain-config>";; esac
cat >"$OUT/genres/xml/network_security_config.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors><certificates src="system" /></trust-anchors>
    </base-config>
$CLEAR
</network-security-config>
EOF

echo "▸ Resources"
cp -R "$ROOT/android/assets" "$OUT/assets"
"$BT/aapt2" compile --dir "$ROOT/android/res" -o "$OUT/res.zip"
"$BT/aapt2" compile --dir "$OUT/genres" -o "$OUT/genres.zip"
"$BT/aapt2" link -o "$OUT/unsigned.apk" \
  -I "$ANDROID_JAR" \
  --manifest "$ROOT/android/AndroidManifest.xml" \
  --java "$OUT/gen/java" \
  -A "$OUT/assets" \
  --min-sdk-version 26 --target-sdk-version 34 \
  --version-code "$VERSION_CODE" --version-name "$VERSION_NAME" \
  "$OUT/res.zip" "$OUT/genres.zip"

echo "▸ Java → dex"
javac -nowarn -Xlint:-options --release 11 -encoding UTF-8 -classpath "$ANDROID_JAR" -d "$OUT/classes" \
  $(find "$ROOT/android/src" "$OUT/gen/java" -name '*.java')
"$BT/d8" --release --min-api 26 --lib "$ANDROID_JAR" --output "$OUT" $(find "$OUT/classes" -name '*.class')
(cd "$OUT" && zip -q unsigned.apk classes.dex)

echo "▸ Align & sign"
"$BT/zipalign" -f -p 4 "$OUT/unsigned.apk" "$OUT/aligned.apk"
if [ ! -f "$KEYSTORE" ]; then
  mkdir -p "$ROOT/keys"
  # head reads a fixed count first; `tr </dev/urandom | head` would die of SIGPIPE under pipefail.
  head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | cut -c1-24 >"$KEYPASS"
  chmod 600 "$KEYPASS"
  keytool -genkeypair -keystore "$KEYSTORE" -storetype PKCS12 -alias saarathi-driver \
    -keyalg RSA -keysize 3072 -validity 12000 \
    -storepass "$(cat "$KEYPASS")" -keypass "$(cat "$KEYPASS")" \
    -dname "CN=Saarathi Driver, O=Saarathi Cabs, L=Chennai, ST=Tamil Nadu, C=IN" >/dev/null 2>&1
  echo "  New signing key created in keys/ — BACK IT UP."
fi
"$BT/apksigner" sign --ks "$KEYSTORE" --ks-pass "file:$KEYPASS" --ks-key-alias saarathi-driver \
  --out "$APK" "$OUT/aligned.apk"
"$BT/apksigner" verify "$APK"
rm -f "$APK.idsig"

echo "✓ $APK ($(du -h "$APK" | cut -f1 | xargs)) → $SERVER_URL/admin"

if [ "${1:-}" = "install" ]; then
  adb install -r "$APK"
  adb shell monkey -p "$PACKAGE" -c android.intent.category.LAUNCHER 1 >/dev/null
fi
